### PR TITLE
Fix for onRun not working after hot code pushes.

### PR DESCRIPTION
**Pull request by fabienb4**
iron-meteor/iron-router#1219

### CODE REVIEW

**Comment by joegoldbeck** [comment]
Not knowing tons about the internals of iron-router, this seems a pretty reasonable fix. As noted in #1130, currently `_hasJustReloaded` can never be set to false again once it is made true by a hot code push. 

@cmather is there anything I can do to help push this PR along (or perhaps a simpler version that just moves `RouteController._hasJustReloaded = false;`)? #1219 means my app effectively breaks after a hot code reload in a way that seems difficult to refactor around (`onRun` is key). Thanks so much for all your hard work on iron-router!

**Comment by cmather** [comment]
Sorry guys :-). Trying not to drown but it's on my task list to do a bunch of merges and another release in the next week or so.

**Comment by joegoldbeck** [comment]
Fair enough! I wish you luck in staying above water and look forward to the next release. Thanks so much for the quick response!

**Comment by cmather** [comment]
will try to put out a fix release soon. sorry we've in product work for a while and so haven't had a chance to keep up with merges.

**Pull request merged**
